# Generated by Django 2.2.6 on 2019-10-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con ese email'}, max_length=254, unique=True, verbose_name='direccion de correo'),
        ),
    ]
