# Generated by Django 2.2.6 on 2019-11-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191123_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinformativo',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='postinformativo',
            name='nombre',
        ),
    ]
