# Generated by Django 2.2.6 on 2019-11-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191124_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
