# Generated by Django 2.2.6 on 2019-11-22 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191121_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='img',
        ),
        migrations.AddField(
            model_name='postimg',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.PostBase'),
            preserve_default=False,
        ),
    ]
