# Generated by Django 2.2.6 on 2019-11-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191125_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
